### ISSUE TITLE
DNS: externe Namensauflösung

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#136]
Nochmal von peter s. erklären lassen warum es nicht geht, und was wir tun können

**Comment by DanielMueller1309** [comment]
hast du schon dns über https getestet?
ansonsten setz ich mich nächste woche nach schule damit mal auseinander

**Comment by quotengrote** [comment]
Nö, probiers

**Comment by quotengrote** [comment]
@Peter S. fragen

**Comment by DanielMueller1309** [comment]
https://docs.pi-hole.net/guides/dns/cloudflared/

**Comment by DanielMueller1309** [comment]
Neue Erkenntnis:
`CLOUDFLARED_OPTS=--port 5053 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query`
gibt folgendes im programmstatus zurück:
``

**Comment by DanielMueller1309** [comment]
<?xml version="1.0" encoding="iso-8859-1"?>
<?xml-stylesheet href="file:///C:/Program Files (x86)/Nmap/nmap.xsl" type="text/xsl"?><nmaprun start="1621947693" profile_name="" xmloutputversion="1.04" scanner="nmap" version="7.91" startstr="Tue May 25 15:01:33 2021" args="nmap -p 443 -T4 11.8.108.254"><scaninfo services="443" protocol="tcp" numservices="1" type="syn"></scaninfo><verbose level="0"></verbose><debugging level="0"></debugging><output type="interactive">Starting Nmap 7.91 ( https://nmap.org ) at 2021-05-25 15:01 MitteleuropÃ¤ische Sommerzeit

Nmap scan report for 11.8.108.254

Host is up (0.0021s latency).



PORT    STATE  SERVICE

443/tcp closed https



Nmap done: 1 IP address (1 host up) scanned in 6.34 seconds

</output><host comment=""><status state="up"></status><address addrtype="ipv4" vendor="" addr="11.8.108.254"></address><hostnames></hostnames><ports><port protocol="tcp" portid="443"><state reason="reset" state="closed" reason_ttl="63"></state><service method="table" conf="3" name="https"></service></port></ports><os></os><uptime lastboot="" seconds=""></uptime><tcpsequence index="" values="" difficulty=""></tcpsequence><ipidsequence values="" class=""></ipidsequence><tcptssequence values="" class=""></tcptssequence></host><runstats><finished timestr="Tue May 25 15:01:39 2021" time="1621947699"></finished><hosts down="0" total="1" up="1"></hosts></runstats></nmaprun>

Erklärt einiges

**Comment by quotengrote** [comment]
Geklärt: habe von D.S. 2x DNS-Server genannt bekommen und mit Daniel getestet ob Sie funktionieren.

10.62.94.6
10.62.94.7

Ich rolle alle Änderungen am 19. und/oder am 21.07.21 aus.

Dazu gehoeren:
#139 
#197 
#141 (prio)
#210

# Doing
Apt-Proxy setzen bei allen außer acng
Dnsmasq-upstream-dns ändern
