### ISSUE TITLE
ansible: Inventory aufteilen

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#184]
Aufteilen in:
  - dynamisches Inventar für VMs: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_inventory.html
  - statisches für alles andere

Zustimmung?

**Comment by DanielMueller1309** [comment]
:+1:

**Comment by Kati-20DP** [comment]
können wir so machen.

**Comment by MaxGoe** [comment]
+1

**Comment by quotengrote** [comment]
:-D https://github.com/KeyboardInterrupt/ansible_xlsx_inventory

**Comment by MaxGoe** [comment]
Haha hört sich gut an hast du das schon mal getestet?

**Comment by quotengrote** [comment]
nö, fand das nur lustig

**Comment by MaxGoe** [comment]
Achso :D ^^
