### ISSUE TITLE
Git-Instanz erstellen

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_ausb_md#197]
Erstellen einer VM mit Git-Instanz als zweiter Remote welche mit _git fetch_ den aktuellen stand von GitHub zieht und mit Jenkins die Ansible Playbooks offline ausrollen kann

**Comment by quotengrote** [comment]
Github --> Mirror zu Gitea --> Jenkins fragt Gitea
damit muss Jenkins nie ins Internet

**Comment by quotengrote** [comment]
gearbeitet wird in GitHUb und alles wird Nmin repliziert

**Comment by quotengrote** [comment]
vm ist erstellt

**Comment by quotengrote** [comment]
hängt an dns

**Comment by quotengrote** [comment]
dns läuft, systemd-unit von gitea startet nicht

**Comment by quotengrote** [comment]
Instanz steht
Nutzer sind erstellt:
max:hallowelt
daniel:hallowelt
kati:hallowelt
mg:hallowelt
tim:hallowelt

Kennwort muss bei der ersten Anmeldung geändert werden

Url: http://blgite001.ausbildung.md:3000
