### ISSUE TITLE
Einrichtung Mirror von GH in Gitea für Jenkins

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#199]

**Comment by quotengrote** [comment]
wer will? (selber oder mit zu gucken)

**Comment by Kati-20DP** [comment]
Ich würde gern mit dabei sein und ggf. auch selber probieren.

**Comment by MaxGoe** [comment]
würde mir das auch mal gern anschauen (wenn möglich)

**Comment by quotengrote** [comment]
Gerne, brauchen dafür aber dns

**Comment by quotengrote** [comment]
dns geht, siehe #197

**Comment by quotengrote** [comment]
siehe #139, mache hier zu
