### ISSUE TITLE
Backup Lösung

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#200]
- [x] VM-Backup
- [ ] Konfig-Backup

und ja, trotz ansible notwendig, da wir auch Konfig haben die wir nicht über ansible sichern: z.B.:
- Jenkins-Konfig
- Gitea-Mirror

Ideen?
VM-Backup --> PVE-Intern auf externen Storage
Konfig --> [restic?](https://git.mgrote.net/mg/ansible/src/branch/master/roles/mgrote.restic)

Fragen, Meinungen, Antworten? Bitte bis zum nächsten Termin mal überlegen.

**Comment by quotengrote** [comment]
Oder ganz stumpf alles zu mir nach Hause kopieren jede Nacht :-D

**Comment by quotengrote** [comment]
@DanielMueller1309 @Kati-20DP @MaxGoe @nemo1103

**Comment by DanielMueller1309** [comment]
backup auf die dd wäre möglich aber wenig sinnvoll falls mal wieder ein Kondensator platz, heißt deine heimspiegel-Lösung wäre sicherer bzw redundanter

**Comment by Kati-20DP** [comment]
redundant ist immer gut.

**Comment by quotengrote** [comment]
etckeeper

**Comment by Kati-20DP** [comment]
ich probiere mich mal an etckeeper
