### ISSUE TITLE
ansible: apt-update nur wenn update >5min her

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#218]
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-cache_valid_time

**Comment by quotengrote** [comment]
@DanielMueller1309 @Kati-20DP @MaxGoe Das ist ne schöne Einstiegsaufgabe, dauert keine 5 Minuten und unfasst max. 3 Zeilen... wie siehts aus?

**Comment by Kati-20DP** [comment]
Ich würde mich da mal ran setzen.

**Comment by Kati-20DP** [comment]
Ich habe was gefunden. Ich bin mir nur nicht ganz sicher, ob das in die apt_source gehört?

**Comment by quotengrote** [comment]
Die Lösung ist schon im ersten Kommentar verlinkt ;-)

**Comment by Kati-20DP** [comment]
Genau den habe ich ja. Gehört der zu apt_sources?

**Comment by quotengrote** [comment]
In alle Rollen die Pakete updaten.

**Comment by Kati-20DP** [comment]
ok.

**Comment by Kati-20DP** [comment]
In der Rolle "update packages" steht schon was mit der  cache_valid time.  Allerdings mit 30.  Ansonsten ist apt_update nur noch unter set_apt_sources. Zumindest habe ich nicht mehr gefunden. Ist das Korrekt?

**Comment by quotengrote** [comment]
Guck ich mir im PR an.
