### ISSUE TITLE
Script-Server statt Jenkins?

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#225]
https://github.com/bugy/script-server

**Comment by quotengrote** [comment]
@DanielMueller1309 @Kati-20DP @nemo1103 @MaxGoe ?

**Comment by DanielMueller1309** [comment]
verstehe zwar noch nicht genau wie das funktioniert aber klingt nicht schlecht die idee

**Comment by quotengrote** [comment]
keine weiteren Rückmeldungen
