### ISSUE TITLE
Discord statt Skype

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#237]
Discord für unseren Runden/TelCom statt Skype, da ist die Bildübertragung schneller

- [x] Raum/Server anlegen?
- [x] einladen?

**Comment by DanielMueller1309** [comment]
klingt gut, kenne mich zwar kaum in Discord aus, scheint aber eigentlich ganz selbsterklärend zu sein. Müssten dann nur mit Ronny absprechen ob das erlaubt ist da es ja um interne dinge geht.

**Comment by MaxGoe** [comment]
benutze es täglich könnte mich auch damit beschäftigen wenn nötig

**Comment by quotengrote** [comment]
@MaxGoe Würdest du das vorbereiten und dann das nächste mal zeigen/vorstellen?

**Comment by MaxGoe** [comment]
Ja kann ich machen @quotengrote

**Comment by MaxGoe** [comment]
Ich erstell für die Woche nach der Berufsschule mal einen kurzen Termin wo wir alles durchgehen können @quotengrote @DanielMueller1309 @Kati-20DP @nemo1103

**Comment by MaxGoe** [comment]
Moin, schon mal kleines Update Server ist so weit erstellt hier ist der Link zum Server: https://discord.gg/DrXmstkrB4 , alles Weitere besprechen wir dann demnächst nicht vergessen, falls ihr nicht euren echten Namen verwendet einen Nickname zu setzen, sodass man euch zuordnen kann. Vorab Vorschläge einfach hier drunter oder mich direkt anschreiben. Ist alles erstmal relativ selbsterklärend.  @quotengrote @DanielMueller1309 @nemo1103

**Comment by quotengrote** [comment]
+1
#251

**Comment by quotengrote** [comment]
Ööööhm...
![2021-06-10 14_28_09-Greenshot](https://user-images.githubusercontent.com/38253905/121524982-284adf80-c9f8-11eb-90ac-7389e5859568.png)

**Comment by quotengrote** [comment]
kann man da auch schreiben?

**Comment by MaxGoe** [comment]
Ja kann man @quotengrote geht der invite bei dir?

**Comment by quotengrote** [comment]
Ja, geht.

**Comment by quotengrote** [comment]
Kannst dann ja welche anlegen

**Comment by MaxGoe** [comment]
Hatte ich bereits konntest die nur nicht sehen weil du keine Berechtigungen hattest

**Comment by quotengrote** [comment]
Webhooks laufen
