### ISSUE TITLE
Überführen der Dataport Projekt Repos in eine Organisation

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#243]
- [x] Name? mit Ausb klären
- [x] Repos umziehen
- [x] Berechtigungen anpassen
- [x] Ownership anpasssen

**Comment by MaxGoe** [comment]
@quotengrote was genau sind die Vorteile/Nachteile dieses überführens? Oder sind wir verpflichtet das zu tun?

**Comment by quotengrote** [comment]
Bisher läuft alles über meinen persönlichen Account. In Zukunft wird das ein Org-Account der dann die Repos besitzt. Dann kann ich dann alles nach der Ausbildung ohne Probleme an die Nachfolger übergeben. Und zusätzlich sind auch mehrere "Admins" möglich.

**Comment by DanielMueller1309** [comment]
oder wenn möglich und die jeweiligen git instanzen von außen erreichbar sind vielleicht direkt in eins der dataport gits gehen?

**Comment by quotengrote** [comment]
Nö, kosten zuviel...

**Comment by quotengrote** [comment]
https://github.com/account/organizations/new?coupon=&plan=team_free
