### ISSUE TITLE
Upgrade PVE6.4 --> 7

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#262]
* https://pve.proxmox.com/wiki/Upgrade_from_6.x_to_7.0

# Anleitung, prüfen ob die Pfade passen

```sudo apt update
sudo apt upgrade
sudo pve6to7 --full
VMs runter migrieren
sudo apt dist-upgrade
sudo sed -i 's/buster\/updates/bullseye-security/g;s/buster/bullseye/g' /etc/apt/sources.list.d/*
sudo sed -i -e 's/buster/bullseye/g' /etc/apt/sources.list.d/pve-no-subscription.list
Pfade in set_apt_sources anpassen
sudo apt update
sudo apt dist-upgrade
sudo apt autoremove
````

**Comment by quotengrote** [comment]
vllt gleich neu installieren und #134 lösen
2 Fliegen mit einer Klappe

Cave: Config natürlich sichern und zurückspielen und FQDNs anpassen

**Comment by quotengrote** [comment]
quorem beachten

`pvecm e 1`

**Comment by quotengrote** [comment]
Mache ich am Mittwoch vor Ort wenn ich es zeitlich hinkriege.

**Comment by quotengrote** [comment]
Doch nicht, dafür haben wir ja alle einen Termin.

**Comment by quotengrote** [comment]
So, wir sollten schon einmal den groben Ablauf vorbereiten:

1. alle VMs auf einen der beiden Nodes schieben
2. Cluster auflösen @MaxGoe 
3. Node herunterfahren und neu installieren @Kati-20DP 
4. Cluster zusammenfügen @DanielMueller1309 
5. VMs verschieben
6. Cluster auflösen @MaxGoe 
7. Node herunterfahren und neu installieren @Kati-20DP 
8. Cluster zusammenfügen @DanielMueller1309 

Ich habe euch alle für die jeweiligen Aufgaben getagged, sucht euch schonmal alle benötigten Befehle und Hinweise zusammen(PVE-Wiki) und schreibt sie irgendwo mit hin wo alle Zugriff haben(da bietet sich ein neues Wiki-Dokument an).

Das ganze bitte bis spätestens nächsten Dienstag.

Bei Fragen mich einfach anschreiben... das ganze soll ordentlich laufen wenn ich schon in die Firma kommen muss.

**Comment by quotengrote** [comment]
Ich bin an dem Tag nur bis ca. 1400 in MD, bis dahin müssen wir fertig sein, also Beginn gleich um 0800.

**Comment by Kati-20DP** [comment]
Ich weiß nicht, ob ich die ganze Zeit dabei sein kann. Muss ich erst klären.

**Comment by quotengrote** [comment]
Kein Problem, die Anleitung kannst du ja vorher schreiben.

Soll ja eh alles zusammengefasst werden für die Doku.

**Comment by quotengrote** [comment]
@all Kann schon jemand den Bootstick vorbereiten mit PVE7*?

**Comment by quotengrote** [comment]
Neue Namen: 
```
BLPVEE001.ausbildung.md
BLPVEE002.ausbildung.md
```

Passt das für alle?

**Comment by Kati-20DP** [comment]
Habe schon PVE 7 runtergeladen. Würde ich mich drum kümmern mit dem Stick. Muss nur aufpassen, das ich das richtige Format wähle.

**Comment by quotengrote** [comment]
Wenn ihr die Anleitungen fertig habt packt die Links hier mit rein.
Dann können wir die vorher nochmal durchgehen.

**Comment by DanielMueller1309** [comment]
mein vorschlag zur cluster configuration da es empfohlen wird:
Wir erstellen bei der Neinstallation ein weiteres Netzwerkinterface, drei NICs müsste jeder Node ja haben, und nehmen uns jeweils einen dedizierten NIC nur für die Clusterkomunikation Dieses NIC bekomment dann eine Adresse in einem 31er netz damit sie nur sich beide kennen, an die NICs kommt ein verbindungslankabel welches sie sich beide erreichen lässt und in der Clusterconfig wird dann einfach gesagt nimm diese interface mit dem 31er netz zur komunikation

**Comment by MaxGoe** [comment]
https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Proxmox-Cluster-aus-Node-entfernen

**Comment by Kati-20DP** [comment]
https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Node-herunterfahren-und-neu-installieren

**Comment by DanielMueller1309** [comment]
anbei der issue für die zweite dedizierte Cluster NIC #357

**Comment by quotengrote** [comment]
> https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Proxmox-Cluster-aus-Node-entfernen

Habe kleinere Typos ('s) entfernt, vllt kannst du noch das entfernen der alten Node-Dateien erwähnen, müssten in `/etc/corosync/` liegen.



> https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Node-herunterfahren-und-neu-installieren
- überflüssiges `*`
- Formatierung (habe ich angepasst)
- Wieso ist noch rufus drin?

**Comment by MaxGoe** [comment]
@quotengrote entfernt man die alten Node Dateien vor oder nach der Node Entfernung

**Comment by quotengrote** [comment]
Nach

---

was ist das eigentlich für Syntax: `>__8.` noch nie gesehen

**Comment by MaxGoe** [comment]
Hab das im Internet gefunden :D

**Comment by MaxGoe** [comment]
> ist halt für Code Blöcke und __ um das Fett zu Highlighten

**Comment by Kati-20DP** [comment]
> > https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Proxmox-Cluster-aus-Node-entfernen
> 
> Habe kleinere Typos ('s) entfernt, vllt kannst du noch das entfernen der alten Node-Dateien erwähnen, müssten in `/etc/corosync/` liegen.
> 
> > https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Node-herunterfahren-und-neu-installieren
> 
> * überflüssiges `*`
> * Formatierung (habe ich angepasst)
> * Wieso ist noch rufus drin?



Ich wollte beide Varianten aufnehmen.

**Comment by quotengrote** [comment]
Ok, die ` haben den Vorteil das du die Sprache im Codeblock angeben kannst

```shell
#!/bin/bash
echo test
```
-->
\```shell
#!/bin/bash
echo test
\```

Dann hast du Syntax-Highlighting im Block

**Comment by quotengrote** [comment]
> Ich wollte beide Varianten aufnehmen. Ich hatte nur zwischendrin gespeichert aber noch nicht weitergemacht.

Dann fehlt aber noch was oder?

**Comment by DanielMueller1309** [comment]
https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/ProxMox---Cluster-erstellen

**Comment by MaxGoe** [comment]
Anleitung nochmal geupdated

**Comment by quotengrote** [comment]
Äh, ja nein :-D

zu 5. : Du willst alle Dateien entfernen? 

zu 6.: passt

**Comment by MaxGoe** [comment]
Ne ich will die Dateien nur auf dem jeweiligen Node entfernen

**Comment by Kati-20DP** [comment]
> > Ich wollte beide Varianten aufnehmen.
> 
> Dann fehlt aber noch was oder?

Ja, war ja noch nicht fertig damit

**Comment by quotengrote** [comment]
Wo willst du die Node-Dateien entfernen?
--> auf dem aus dem Cluster entfernten Node? --> nicht nötig wird eh neuinstalliert
--> auf dem anderen? --> da würdest du den Cluster löschen

`/etc/pve/corosync.conf` ist aber das FUSE-Dateisystem über alle Nodes. Was du da entfernst ist überall weg.
Ich würde das entfernen auch als allerletzten Schritt ansetzen.

**Comment by quotengrote** [comment]
> Ja, war ja noch nicht fertig damit

Dann schicks doch nicht weg :-D

**Comment by Kati-20DP** [comment]
> > Ja, war ja noch nicht fertig damit
> 
> Dann schicks doch nicht weg :-D

**Comment by Kati-20DP** [comment]
sorry. Schneller finger

**Comment by MaxGoe** [comment]
> Wo willst du die Node-Dateien entfernen? --> auf dem aus dem Cluster entfernten Node? --> nicht nötig wird eh neuinstalliert --> auf dem anderen? --> da würdest du den Cluster löschen
> 
> `/etc/pve/corosync.conf` ist aber das FUSE-Dateisystem über alle Nodes. Was du da entfernst ist überall weg.
> 
> Ich würde das entfernen der NODE-Files auch als allerletzten Schritt ansetzen.

Das heißt die .conf lass ich und entferne nur alles in der corosync ?

**Comment by MaxGoe** [comment]
Nochmal geupdated

**Comment by quotengrote** [comment]
> Nochmal geupdated

Der befehl `rm` fehlt, sonst passts.

**Comment by quotengrote** [comment]
@Kati-20DP angepasst?

**Comment by Kati-20DP** [comment]
> @Kati-20DP angepasst?

rufus ja, der Rest noch nicht.

**Comment by MaxGoe** [comment]
> > Nochmal geupdated
> 
> Der befehl `rm` fehlt, sonst passts.

geändert

**Comment by Kati-20DP** [comment]
> @Kati-20DP angepasst?

Muss jetzt noch das machen, was nach der Installation gemacht werden muss.

**Comment by quotengrote** [comment]
Frage oder Aussage?

**Comment by Kati-20DP** [comment]
> Frage oder Aussage?

Aussage!

**Comment by Kati-20DP** [comment]
Bitte einmal schauen, ob das so gemeint ist.

**Comment by quotengrote** [comment]
ich gehe mal davon aus das du Feedback willst:

Zeile 15: GPT/MBR ist klar, aber welchen brauchen unsere Server?
Zeile 16: NTFS für nen Linux-Bootstick?
Zeile: 30: LVM und ZFS auswählen???
Zeile 32: Email weg
36: netzmaske ist /24, einfach die bits zählen

**Comment by quotengrote** [comment]
habs selber angepasst...

**Comment by quotengrote** [comment]
Anleitung: https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/upgrade-umzug-zusammengefasst

**Comment by quotengrote** [comment]
Status:
- apt.conf wurde zu spät während des bootstrapping erstellt
- Server sind DIREKT per Kabel verbunden(nicht über Switch)(Kabel = Rot und Mitte)
-

**Comment by quotengrote** [comment]
link0 192
link 11.10
