### ISSUE TITLE
ansible ara

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#299]
- https://github.com/ansible-community/ara
- https://hub.docker.com/r/recordsansible/ara-api

Zum loggen aller ansible-Aktionen, egal ob cli oder ci.

Kann ich bei Bedarf auch einmal vorführen.

Integration ist toteinfach :-D

**Comment by quotengrote** [comment]
https://git.mgrote.net/mg/docker-ansible-ara

**Comment by quotengrote** [comment]
Fehlermeldung?

**Comment by Kati-20DP** [comment]
TLS Verbindung kann nicht mit github hergestellt werden.
Dann gab es noch diese Fehlermeldung: obacht: unable to make secure connection to remote host und lynx unzugängliche startdatei http://www.github.com

**Comment by Kati-20DP** [comment]
Meldung:
![Screenshot (237)](https://user-images.githubusercontent.com/72388550/133092966-1a8cdfcd-07be-4742-b7ce-a153fc18fe1a.png)

**Comment by Kati-20DP** [comment]
Fehler: so wie es aussieht führt er das Playbook für ara nicht aus.

**Comment by Kati-20DP** [comment]
Python 3.8.10
ansible 2.11.3
jinja version 2.11.2
ara 1.5.7
Kann es sein, dass die Versionen nicht zusammen passen?
Oder Fehlen die Ansible Plugins?

**Comment by Kati-20DP** [comment]
Jetzt scheint es zumindest bis zum Playbook auszuführen. 
Mit der Verwendung von ara-playbook list kommt das:
![Screenshot (246)](https://user-images.githubusercontent.com/72388550/133418901-e40858fb-4f09-4b87-8c2b-0f19eaf27434.png)

**Comment by Kati-20DP** [comment]
Mit Docker: Folgende Fehlermeldung:

# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c apt-get update -qq >/dev/null
E: The repository 'cdrom://Ubuntu-Server 20.04.1 LTS _Focal Fossa_ - Release amd64 (20200731) focal Release' does not have a Release file.

**Comment by Kati-20DP** [comment]
Mit Docker geht es nur bis:

ara is up-to-date
Attaching to ara
ara               | [ara] No setting found for SECRET_KEY. Generating a random k                                     ey...
ara               | [ara] Writing default settings to /opt/ara/settings.yaml
ara               | [ara] Using settings file: /opt/ara/settings.yaml
ara               | Operations to perform:
ara               |   Apply all migrations: admin, api, auth, contenttypes, db,                                      sessions
ara               | Running migrations:
ara               |   Applying contenttypes.0001_initial... OK
ara               |   Applying auth.0001_initial... OK
ara               |   Applying admin.0001_initial... OK
ara               |   Applying admin.0002_logentry_remove_auto_add... OK
ara               |   Applying admin.0003_logentry_add_action_flag_choices... OK
ara               |   Applying api.0001_initial... OK
ara               |   Applying api.0002_remove_host_alias... OK
ara               |   Applying api.0003_add_missing_result_properties... OK
ara               |   Applying api.0004_duration_in_database... OK
ara               |   Applying api.0005_unique_label_names... OK
ara               |   Applying api.0006_remove_result_statuses... OK
ara               |   Applying api.0007_add_expired_status... OK
ara               |   Applying api.0008_playbook_controller... OK
ara               |   Applying api.0009_latesthost... OK
ara               |   Applying api.0010_result_delegated_to... OK
ara               |   Applying contenttypes.0002_remove_content_type_name... OK
ara               |   Applying auth.0002_alter_permission_name_max_length... OK
ara               |   Applying auth.0003_alter_user_email_max_length... OK
ara               |   Applying auth.0004_alter_user_username_opts... OK
ara               |   Applying auth.0005_alter_user_last_login_null... OK
ara               |   Applying auth.0006_require_contenttypes_0002... OK
ara               |   Applying auth.0007_alter_validators_add_error_messages...                                      OK
ara               |   Applying auth.0008_alter_user_username_max_length... OK
ara               |   Applying auth.0009_alter_user_last_name_max_length... OK
ara               |   Applying auth.0010_alter_group_name_max_length... OK
ara               |   Applying auth.0011_update_proxy_permissions... OK
ara               |   Applying db.0001_initial... OK
ara               |   Applying sessions.0001_initial... OK
ara               | [2021-09-15 13:15:18 +0000] [1] [INFO] Starting gunicorn 20.                                     0.4
ara               | [2021-09-15 13:15:18 +0000] [1] [INFO] Listening at: http://                                     0.0.0.0:8000 (1)
ara               | [2021-09-15 13:15:18 +0000] [1] [INFO] Using worker: sync
ara               | [2021-09-15 13:15:18 +0000] [8] [INFO] Booting worker with p                                     id: 8
ara               | [2021-09-15 13:15:18 +0000] [9] [INFO] Booting worker with p                                     id: 9
ara               | [2021-09-15 13:15:19 +0000] [10] [INFO] Booting worker with                                      pid: 10
ara               | [2021-09-15 13:15:19 +0000] [11] [INFO] Booting worker with                                      pid: 11
ara               | [2021-09-15 13:28:59 +0000] [1] [INFO] Handling signal: term
ara               | [2021-09-15 13:28:59 +0000] [9] [INFO] Worker exiting (pid:                                      9)
ara               | [2021-09-15 13:28:59 +0000] [8] [INFO] Worker exiting (pid:                                      8)
ara               | [2021-09-15 13:28:59 +0000] [11] [INFO] Worker exiting (pid:                                      11)
ara               | [2021-09-15 13:28:59 +0000] [10] [INFO] Worker exiting (pid:                                      10)
ara               | [2021-09-15 13:28:59 +0000] [1] [INFO] Shutting down: Master
ara               | [ara] Using settings file: /opt/ara/settings.yaml
ara               | Operations to perform:
ara               |   Apply all migrations: admin, api, auth, contenttypes, db,                                      sessions
ara               | Running migrations:
ara               |   No migrations to apply.
ara               | [2021-09-15 13:29:04 +0000] [1] [INFO] Starting gunicorn 20.                                     0.4
ara               | [2021-09-15 13:29:04 +0000] [1] [INFO] Listening at: http://                                     0.0.0.0:8000 (1)
ara               | [2021-09-15 13:29:04 +0000] [1] [INFO] Using worker: sync
ara               | [2021-09-15 13:29:04 +0000] [10] [INFO] Booting worker with                                      pid: 10
ara               | [2021-09-15 13:29:04 +0000] [11] [INFO] Booting worker with                                      pid: 11
ara               | [2021-09-15 13:29:04 +0000] [12] [INFO] Booting worker with                                      pid: 12
ara               | [2021-09-15 13:29:04 +0000] [13] [INFO] Booting worker with                                      pid: 13
ara               | [2021-09-15 13:42:00 +0000] [1] [INFO] Handling signal: term
ara               | [2021-09-15 13:42:00 +0000] [10] [INFO] Worker exiting (pid:                                      10)
ara               | [2021-09-15 13:42:00 +0000] [11] [INFO] Worker exiting (pid:                                      11)
ara               | [2021-09-15 13:42:00 +0000] [12] [INFO] Worker exiting (pid:                                      12)
ara               | [2021-09-15 13:42:00 +0000] [13] [INFO] Worker exiting (pid:                                      13)
ara               | [2021-09-15 13:42:00 +0000] [1] [INFO] Shutting down: Master
ara               | [ara] Using settings file: /opt/ara/settings.yaml
ara               | Operations to perform:
ara               |   Apply all migrations: admin, api, auth, contenttypes, db,                                      sessions
ara               | Running migrations:
ara               |   No migrations to apply.
ara               | [2021-09-15 13:46:16 +0000] [1] [INFO] Starting gunicorn 20.                                     0.4
ara               | [2021-09-15 13:46:16 +0000] [1] [INFO] Listening at: http://                                     0.0.0.0:8000 (1)
ara               | [2021-09-15 13:46:16 +0000] [1] [INFO] Using worker: sync
ara               | [2021-09-15 13:46:16 +0000] [8] [INFO] Booting worker with p                                     id: 8
ara               | [2021-09-15 13:46:16 +0000] [9] [INFO] Booting worker with p                                     id: 9
ara               | [2021-09-15 13:46:16 +0000] [10] [INFO] Booting worker with                                      pid: 10
ara               | [2021-09-15 13:46:16 +0000] [11] [INFO] Booting worker with                                      pid: 11

**Comment by Kati-20DP** [comment]
Dauert das wirklich so lange??

**Comment by quotengrote** [comment]
Keine Ahnung was du da machst, hatte das alles in 10min deployed :-D

**Comment by Kati-20DP** [comment]
Keine Ahnung was ich da mache und ich weiß auch leider nicht warum das so lange dauert. 
Auf'm Dorf geht halt alles etwas langsamer ;-).
Er scheint es ja aber zu machen oder sehe ich das falsch?

**Comment by quotengrote** [comment]
Stell mir doch mal nen Termin rein, dann gehen wir das systematisch durch.

Aber mit einem System wo ich auch per Skype die Ein/Ausgaben sehen kann.

**Comment by Kati-20DP** [comment]
@quotengrote reicht es dir über AnyDesk?

**Comment by quotengrote** [comment]
So lange ich den richtigen Bildschirm sehe...

**Comment by quotengrote** [comment]
@Kati-20DP Wie heißt der Branch bzw. hast du den schon gepushed? Ich will das für unseren Termin kontrollieren/neu bauen.

**Comment by quotengrote** [comment]
Machen Kati und ich am Mittwoch.

**Comment by quotengrote** [comment]
Bei der "Baremetal"-Lösung muss noch sichergestellt werden das die Anwendung einen eigenen Nutzer hat und auch nur mit dessen rechten läuft.

**Comment by Kati-20DP** [comment]
Werde mich weiter darum kümmern sobald ich wieder im Büro bin. Kann ich leider von zu Hause aus nicht machen.

**Comment by quotengrote** [comment]
vllt auf eingener Technik testen, ersetze Ich(mg) beim nächsten Vor-Ort-Besuch durch #326
