### ISSUE TITLE
Einführung neuer Azubi - Ablaufplan

### ISSUE THREAD

**Issue by MaxGoe** [Azubis-Dataport-Magdeburg/dp_ausb_md#306]
- [x] Liste erstellen wer ihm was erklärt.
- [x] Terminfindung (Wann Einführung stattfindet, min 1 Tag vermutlich mehr)
- [x] Themen

**Comment by quotengrote** [comment]
auf was wird hier gewartet?

**Comment by quotengrote** [comment]
eine kurze Mail mit Materialien habe ich schon geschickt, ihr steht im CC

**Comment by quotengrote** [comment]
RR am 09.12.2021

**Comment by MaxGoe** [comment]
Grober Ablauf erstmal definiert, weiteres folgt

**Comment by MaxGoe** [comment]
https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/Ablaufplan-Einf%C3%BChrung-Azubi

**Comment by MaxGoe** [comment]
Zeitansatz einzelne Aufgaben noch hinzufügen

**Comment by quotengrote** [comment]
Termin bis 10.02.2022 erstellt @Kati-20DP

**Comment by Kati-20DP** [comment]
@quotengrote willst du mit dabei sein?

**Comment by quotengrote** [comment]
Wenn es zeitlich passt
