### ISSUE TITLE
ansible tracing

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#307]
Interesse: https://github.com/mhansen/ansible-trace ?

**Comment by MaxGoe** [comment]
Wie hoch sind denn die Performance einbußen

**Comment by MaxGoe** [comment]
@Kati-20DP @DanielMueller1309 Meinung

**Comment by quotengrote** [comment]
Erledigt in <15min...

Doku: https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/wiki/ansible-trace

Kann nach dem mergen und der nächsten Runde zu.
