### ISSUE TITLE
Neuen Azubi in Organisation + Rollengruppen aufnehmen

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#323]
@MaxGoe brauche den Zugang/Nutzernamen von Ihm, den Rest mache ich.

**Comment by MaxGoe** [comment]
@quotengrote timtho13

**Comment by quotengrote** [comment]
Ist eingeladen...
@timtho13 melde dich bei mir wenn du die Einladung angenommen hast(ab Montag)

**Comment by quotengrote** [comment]
@quotengrote noch zum Admin machen...

**Comment by quotengrote** [comment]
erledigt
