### ISSUE TITLE
Status Mittwoch

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#333]
#197  + #334 - Gitea installiert (siehe Startkennwörter in #197)
#314 + #302 - Jenkins Disk erweitert(2. Platte an VG gehangen)
#320 - cv4pve
#330 + #331 - dependabot
#139 - Update Aufbau Mirror
#335 - Tim
#337 - autoremove
#344 + #332- Proxy Bugfix

Und alle so YEAH; es konnte alles am Ende ohne Fehler ausgerollt werden, MASTER ist wieder stable, den nächsten ders versaut verfluche ich.

**Comment by quotengrote** [comment]
@Kati-20DP + @MaxGoe bei Fragen gerne nächste Woche, sonst dann zu.

**Comment by MaxGoe** [comment]
> 
> 
> #197 + #334 - Gitea installiert (siehe Startkennwörter in #197) #314 + #302 - Jenkins Disk erweitert(2. Platte an VG gehangen) #320 - cv4pve #330 + #331 - dependabot #139 - Update Aufbau Mirror #335 - Tim #337 - autoremove #344 + #332- Proxy Bugfix
> 
> Und alle so YEAH; es konnte alles am Ende ohne Fehler ausgerollt werden, MASTER ist wieder stable, den nächsten ders versaut verfluche ich.

^^ :D

**Comment by MaxGoe** [comment]
Kann erstmal zu mMn
