### ISSUE TITLE
Antrag ZKS Kati

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#359]

**Comment by Kati-20DP** [comment]
Antrag ist gestellt.

**Comment by quotengrote** [comment]
- [x] Antrag wird bearbeitet
- [ ] ZKS Ausweis erhalten

**Comment by Kati-20DP** [comment]
noch nicht da.

**Comment by Kati-20DP** [comment]
Musste noch einmal beantragt werden, da angeblich nicht angekommen ist. Neubeantragt am 04.04.2022

**Comment by Kati-20DP** [comment]
liegt im GeZi

**Comment by Kati-20DP** [comment]
ist da
