### ISSUE TITLE
Netzwerküberblick Doku hinzufügen

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_ausb_md#361]
da nicht direkt aus der Doku erkenntlich noch Netzplan in Hauptdoku seite (tabelle)

**Comment by quotengrote** [comment]
mit Links auf IP-Plan und DNSmasq-Vars und Übersicht aus der Doku

**Comment by quotengrote** [comment]
siehe #338
