### ISSUE TITLE
Umstellung Doku von Wiki zu mkdocs/GitHub Pages

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#365]
# Umstellung Doku von Wiki zu mkdocs/GitHub Pages

Da könnten wir die gleichen Mechanismen wie bei den neueren DP-Dokus nutzen/üben.

**Comment by Kati-20DP** [comment]
Können wir machen.

**Comment by MaxGoe** [comment]
+1

**Comment by quotengrote** [comment]
URL: https://azubis-dataport-magdeburg.github.io/dp_ausb_md/

**Comment by quotengrote** [comment]
# ToDo

- [ ] Erklärung Nutzung
- [ ] Umzug Dateien
