### ISSUE TITLE
VM Windows XP für IPMI

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#385]
Durch Zufall habe ich die Windows XP VM mit Java usw. für die alten IPMIs wiedergefunden.

- [ ] wo speichern?
- [ ] auf PVE?
- [ ] + lokal?

**Comment by quotengrote** [comment]
@DanielMueller1309 @Kati-20DP @MaxGoe @timtho13 ?

**Comment by quotengrote** [comment]
wenn der Storage bereitgestellt ist(08.02.2022) kopieren, dann lokal löschen

**Comment by MaxGoe** [comment]
@quotengrote kannst du die VM hochladen?
