### ISSUE TITLE
Automatisch Updates von Ansible-Collections

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_ausb_md#403]
Wie ich gerade feststellen musste haben wir auf dem Ansible Host immernoch community.general version 1.1 gehabt weshalb auch enige versionsprobleme bestehen dürften bei neueren rollen die bereits neue parameter nutzen.

**Comment by quotengrote** [comment]
Möglichkeiten:
- requirements.yml
  - dann aber mit Version-Pinning(Minor zulassen, Major nur händisch updaten)
- in Repo eingechecked

- [ ] Doku

**Comment by quotengrote** [comment]
Am 10.02.2022 eine Entscheidung treffen. @Kati-20DP @DanielMueller1309 @DanielMueller1309 @timtho13

**Comment by MaxGoe** [comment]
Ergebnis DIESEN Mittwoch den 16.02.2022 @timtho13 @Kati-20DP @DanielMueller1309 @MaxGoe

**Comment by MaxGoe** [comment]
Entscheidung für Requirements.yml
