### ISSUE TITLE
Rolle: create_vms nutzen?

### ISSUE THREAD

**Issue by quotengrote** [Azubis-Dataport-Magdeburg/dp_ausb_md#421]
Soll die Rolle `create_vms` genutzt werden:

Ja --> @DanielMueller1309 PR fertigmachen
Nein --> @DanielMueller1309 alles raus

**Comment by quotengrote** [comment]
Info bis 10.02.2022

**Comment by Kati-20DP** [comment]
Was soll die Rolle genau machen?

**Comment by quotengrote** [comment]
bleibt
