### ISSUE TITLE
Status: 08.02.2022

### ISSUE THREAD

**Issue by DanielMueller1309** [Azubis-Dataport-Magdeburg/dp_ausb_md#425]
### Status nach Storage einbindung in Netzwerk
- Um es einfach zu sagen: alles kaputt.
Wir wollte während wir den Storage machten, zugleich die Anbindung via Fiber Channel zu den Servern sicherstellen. Beim Herunterfahren, einbauen der FC-Card in BLPVEE002 und erneutem hochfahren verlief alles wie gewünscht. 
Als wir BLPVEE001 dem gleichen Prozedere unterziehen wollten ergab sich das dieser nunmehr 'testvm' mit der selben IP wie BLPVEE001 als Hostnamen führe und meint:
```
pve-cluster.service: Failed with result 'exit-code'. 
Failed to start The Proxmox VE cluster filesystem.   
```

- Außerdem gibt es keine laufenden PVE Dienste/VMs somit auch kein DNS/DHCP und Webserver sondern nur die Connection via ssh  
- Vermutung: beim erkennen der FC-Card wird PVE warscheinlich seine mountpoins verworfen oder neugesetz haben.
- Syslog Meldung anbei als Datei (alles ab Zeit: `Feb  8 11:30:43` ist wichtig für den Boot):  [syslog.log](https://github.com/Azubis-Dataport-Magdeburg/dp_ausb_md/files/8023939/syslog.log)
- FC-Card wieder ausbauen veränderte nichts an dem weiteren Zustand. 
- Storage als solches wurde mit Netzwerkeinstellungen sowie Hostnamen versehen.
    -  IP: 11.10.31.5
    - Hostname: BASTOR001

### Open tasks:

- [ ] Storage muss noch weiter konfiguriert
- [ ] BLPVEE001 muss wieder als solches im Cluster zur verfügung stehen.
- [ ] Passwort / Username in Keepass
- [ ] Funktionsfähiges Netzwerk wiederherstellen

**Comment by DanielMueller1309** [comment]
Falls ich noch was vergessen habe sagt gerne bescheid

**Comment by MaxGoe** [comment]
Wer ist dann Morgen mit Daniel und mir Vorort?

**Comment by Kati-20DP** [comment]
Kann ich erst heute Nachmittag entscheiden.

**Comment by DanielMueller1309** [comment]
@MaxGoe wichtig ist vor allem das wir überhaupt morgen in den raum rein kommen. Wenn ich dann morgen den restlichen Tag allein vor diesem Server stehe ist das ja erstmal egal hauptsache wir kommen erst mal ran.
Sagen wir dann erst mal morgen wieder 8:00?

**Comment by MaxGoe** [comment]
@DanielMueller1309 Ja ich bin morgen da

**Comment by Kati-20DP** [comment]
bin auch da

**Comment by DanielMueller1309** [comment]
SSH verbindung zum server wurde wegen zu offener rechte auf das system unterbunden. 
Fehler behoben.
Weiterhin besteht die Problematik das die /etc/cloud/cloud.cfg die dateien: `hosts` und `hostname` mit daten wie Testvm überschreibt Fehleranalyse warum und wie das zu verhindern ist läuft.

**Comment by MaxGoe** [comment]
Wenn in cloud.cfg Parameter preserve_hostname : True gesetzt wird findet kein Überschreiben statt

**Comment by MaxGoe** [comment]
wird geschlossen siehe #436
