### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Kati-20DP** [Azubis-Dataport-Magdeburg/dp_ausb_md#432]
Die Manuals werden nicht angezeigt, kommt nur ein Fehler 404.

**Comment by MaxGoe** [comment]
PDFs können nicht in Github Pages geöffnet werden somit Verweis auf Repo

**Comment by Kati-20DP** [comment]
scheint alles richtig zu sein, es ist trotzdem nicht möglich, eine PDF aufzumachen.

**Comment by Kati-20DP** [comment]
Fehler gefunden. Der link war falsch gesetzt. Alles geändert, jetzt gehen die Links wieder.
